### ISSUE TITLE
Team map CSVs not included in package installation

### ISSUE THREAD

**Issue by RHThree** [dcstats/CBBpy#59]
Ran into issues at first when I tried to get the current schedule for the Ohio State men's basketball team
```python
import cbbpy.mens_scraper as cbb
item = cbb.get_games_team('ohio state')
print(item)
```
With the following error:
```
(cbb-env) russel@Russels-MacBook-Pro cbb-model % python3 data_import.py
Log file is located at /Users/russel/Library/Logs/CBBpy/2.1.0/CBBpy.log
Traceback (most recent call last):
  File "/Users/russel/Documents/GitHub/cbb-model/data_import.py", line 2, in <module>
    item = cbb.get_games_team('ohio state')
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/cbbpy/mens_scraper.py", line 133, in get_games_team
    return _get_games_team(team, season, "mens", info, box, pbp)
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/utils/cbbpy_utils.py", line 127, in wrapper
    result = func(*args, **kwargs)
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/utils/cbbpy_utils.py", line 265, in _get_games_team
    schedule_df = _get_team_schedule(team, season, game_type)
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/utils/cbbpy_utils.py", line 663, in _get_team_schedule
    team_id, team_name = _get_id_from_team(team, season, game_type)
                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/utils/cbbpy_utils.py", line 1522, in _get_id_from_team
    team_map_df = _get_team_map(game_type)
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/utils/cbbpy_utils.py", line 1516, in _get_team_map
    return pd.read_csv(data_path)
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ~~~~~~~~~~^
        f,
        ^^
    ...<6 lines>...
        storage_options=self.options.get("storage_options", None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
FileNotFoundError: [Errno 2] No such file or directory: '/Users/russel/Documents/GitHub/cbb-model/cbb-env/lib/python3.13/site-packages/utils/mens_team_map.csv'
```
After some digging I found that the team map csvs were not included in my package installation (regardless of the way I tried to install it). I am curious if this has to do with a few factors specific to my project:

1. Using macOS and Homebrew (which this library is not available on)
2. Using a Virtual Environment for package management (because of the homebrew warnings from trying to install a pip package)

This may be an easy fix with a simple modification to the pyproject.toml file (take this with a grain of salt though given it was heavily chatgpt assisted). It suggests to add the following to the toml:

```
[tool.setuptools]
include-package-data = true  # This tells setuptools to include non-Python files

[tool.setuptools.package-data]
"utils" = ["*.csv"]  # Includes all CSV files in the utils folder
```

**Comment by dcstats** [comment]
agh, can't believe I didn't catch this. thanks for opening this issue - will get it resolved ASAP @RHThree

**Comment by dcstats** [comment]
fixed with #60
